POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer <setTokenValueHere>

{
  "title": "New blog with token",
  "author": "Tester",
  "url": "www",
  "likes": 55
}